name: Docker Image CI

on:
  push:
    # Trigger unless only the wiki directory changed
    paths:
      - "uk_bin_collection_api_server/**"
      - ".github/workflows/docker-image.yml"
    branches: [ "master" ]
  pull_request:
    # Trigger unless only the wiki directory changed
    paths:
      - "uk_bin_collection_api_server/**"
    # The branches below must be a subset of the branches above
    branches: [ "master" ]
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 0' # This runs at 00:00 on Sunday every week

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v5
    - name: Publish to Registry
      uses: elgohr/Publish-Docker-Github-Action@v5
      with:
        name: robbrad182/uk-bin-collection
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_API_KEY }}
        workdir: uk_bin_collection_api_server
